### PR TITLE
Bump of the wkhtmltopdf binary to version 0.12.2.4

### PR DESCRIPTION
**Pull request by brokermint**
This fixes an issue with black background of the transparent areas of the png images

### CODE REVIEW

**Comment by pallymore** [comment]
awesome :) tested in my VM, works pretty well. merging.

Thanks!

**Comment by brokermint** [comment]
Awesome! :)

**Comment by pallymore** [comment]
it seems I don't have the permission to push the gem to rubygems.

@rposborne could you publish it?

**Comment by rposborne** [comment]
@pallymore done.

**Comment by pallymore** [comment]
awesome :3

**Pull request merged**
